name: Ping Supabase Database

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase database to keep it active
        run: |
          curl -v -X POST 'https://sajziwnbtfxhupvsyqfa.supabase.co/rest/v1/rpc/ping' \
          -H "Content-Type: application/json" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
